services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqqq
    environment:
      - RABBITMQ_DEFAULT_USER=${RabbitMqOptions__Username}
      - RABBITMQ_DEFAULT_PASS=${RabbitMqOptions__Password}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - vladify-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MongoDbOptions__Username}
      - MONGO_INITDB_ROOT_PASSWORD=${MongoDbOptions__Password}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vladify-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Vladify.NotificationAPI/Dockerfile
    container_name: vladify-notification-api
    env_file:
      - .env
    environment:
      - RabbitMqOptions__ServerHost=rabbitmq
      - MongoDbOptions__ConnectionString=mongodb://${MongoDbOptions__Username}:${MongoDbOptions__Password}@mongodb
    ports:
      - "8083:8080"
    networks:
      - vladify-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  vladify-network:
    external: true
